# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: INTLUG - The International Linux Users Group
description: >- # this means to ignore newlines until "baseurl:"
  INTLUG is an attempt to make a Linux User Group that isn't constrained to 
  geographical borders. It's a forum for anything Linux
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://intlug.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# todo, replace logos
logo: "/assets/img/branding/intlug-banner.png"
logo-icon: "/assets/img/branding/intlug-logo.png"
logo-icon-SEO: "/assets/img/branding/intlug-symbol-black.png" # must be a non SVG file

# Disable newsletter
mailchimp: null


night_mode: "auto" 
logo-dark: "/assets/img/branding/intlug-logo.png"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
author: Peter Larsen # add your name
author-pic: Peter.png
about-author: Open Source fanboy, working with Linux since the mid 1990s. Have the pleasure of working with Open Source in my dayjob; covering infrastructure/Linux as well as development platforms. From containers, kubernetes to storage and networking.
email: peter@peterlarsen.org
github:  bit4man
website: "https://intlug.github.io"

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

extensions:
  mermaid_enable: true

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: US/Eastern

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
